site_name: lernOS Achtsamkeit42

docs_dir: src

site_dir: ../docs/de

nav:
    - Achtsamkeit 4.2 - Dein Weg ist das Ziel: index.md
    - lernOS: 
        - lernOS Grundlagen: 2-_-lernOS-Grundlagen.md
        - lernOS Wheel Mindset Skillset und Toolset    : 2-1-lernOS-Wheel.md
        - Die Macht von Peer Support: 2-2-lernOS-Circle.md
        - lernOS Lizenz: 2-3-lernOS-Lizenz.md
    - Lernpfad Achtsamkeit:
        - Lernpfad Achtsamkeit: 3-_-Lernpfad_Achtsamkeit.md
        - Woche 0 - Der Circle gr체ndet sich: 3-00-Circle-Gruendung.md
        - Woche 1 - Energie aufbauen und Klarheit: 3-01-Energie-Klarheit.md
        - Woche 2 - F체hle und erfahre Dich: 3-02-Fuehle-erfahre.md
        - Woche 3 - Ablenkung und Widerst채nde - Ich bleibe fokussiert: 3-03-Ablenkung_Widerstaende.md
        - Woche 4 - Die Lebendigkeit des Moments: 3-04-Lebendigkeit-des-Moments.md
        - Woche 5 - Achtsamkeit im Handeln: 3-05-Achtsam-Handeln.md
        - Woche 6 - Check-up und Reflexion: 3-06-Checkup-Reflexion.md
        - Woche 7 - Balance und achtsame Kommunikation: 3-07-Balance-Kommunikation.md
        - Woche 8 - Schatten Teil 1 - Erkennen deiner eigenen Trigger: 3-08-Schatten-Trigger.md
        - Woche 9 - Schatten Teil 2 - (Selbst-)Wirksamkeit: 3-09-Schatten-SelbstWirksamkeit.md
        - Woche 10 - Integration und Werte: 3-10-Integration-Werte.md
        - Woche 11 - Achtsamkeit und Priorit채ten im Alltag: 3-11-Prioritaeten-Alltag.md
        - Woche 12 - Am Ende steht der Anfang - gemeinsamer Austausch: 3-12-Ende-Anfang.md
    - Stop talking, start doing!: 4-_-Stop-talking.md

theme:
    name: 'material'
    palette:
        primary: 'deep orange'
        accent: 'deep orange'
    language: de

repo_name: 'cogneon/lernos-achtsamkeit42'
repo_url: 'https://github.com/cogneon/lernos-achtsamkeit42'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/lern_os
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/showcase/lern-os
        - icon: fontawesome/brands/github
          link: https://github.com/cogneon
    disqus: lernos